import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "../components/ui/sidebar";
import { AppSidebar } from "../components/SideBar";
import { Navbar } from "../components/Navbar";
import {TooltipProvider} from "../components/ui/tooltip"

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Product Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <TooltipProvider delayDuration={0}>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger/>
          <SidebarInset>
            <Navbar />
            <main className="flex-1 overflow-auto bg-slate-50">
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
        </TooltipProvider>
        
      </body>
    </html>
  );
}